"use strict";
exports.__esModule = true;
var DashboardWidgetTypeEnum;
(function (DashboardWidgetTypeEnum) {
    DashboardWidgetTypeEnum[DashboardWidgetTypeEnum["None"] = 0] = "None";
    DashboardWidgetTypeEnum[DashboardWidgetTypeEnum["Grid"] = 1] = "Grid";
    DashboardWidgetTypeEnum[DashboardWidgetTypeEnum["BarChart"] = 2] = "BarChart";
    DashboardWidgetTypeEnum[DashboardWidgetTypeEnum["PieChart"] = 3] = "PieChart";
    DashboardWidgetTypeEnum[DashboardWidgetTypeEnum["Gauge"] = 4] = "Gauge";
    DashboardWidgetTypeEnum[DashboardWidgetTypeEnum["Pivot"] = 5] = "Pivot";
    DashboardWidgetTypeEnum[DashboardWidgetTypeEnum["TreeMap"] = 6] = "TreeMap";
    DashboardWidgetTypeEnum[DashboardWidgetTypeEnum["ScatterChart"] = 7] = "ScatterChart";
    DashboardWidgetTypeEnum[DashboardWidgetTypeEnum["Cards"] = 8] = "Cards";
    DashboardWidgetTypeEnum[DashboardWidgetTypeEnum["TextBox"] = 9] = "TextBox";
    DashboardWidgetTypeEnum[DashboardWidgetTypeEnum["Image"] = 10] = "Image";
    DashboardWidgetTypeEnum[DashboardWidgetTypeEnum["Group"] = 11] = "Group";
    DashboardWidgetTypeEnum[DashboardWidgetTypeEnum["GeoPointMap"] = 12] = "GeoPointMap";
    DashboardWidgetTypeEnum[DashboardWidgetTypeEnum["ChoropethMap"] = 13] = "ChoropethMap";
    DashboardWidgetTypeEnum[DashboardWidgetTypeEnum["BubbleMap"] = 14] = "BubbleMap";
    DashboardWidgetTypeEnum[DashboardWidgetTypeEnum["PieMap"] = 15] = "PieMap";
    DashboardWidgetTypeEnum[DashboardWidgetTypeEnum["StatisticsChart"] = 16] = "StatisticsChart";
    DashboardWidgetTypeEnum[DashboardWidgetTypeEnum["RangeFilter"] = 17] = "RangeFilter";
    DashboardWidgetTypeEnum[DashboardWidgetTypeEnum["ComboBox"] = 18] = "ComboBox";
    DashboardWidgetTypeEnum[DashboardWidgetTypeEnum["ListBox"] = 19] = "ListBox";
    DashboardWidgetTypeEnum[DashboardWidgetTypeEnum["TreeView"] = 20] = "TreeView";
    DashboardWidgetTypeEnum[DashboardWidgetTypeEnum["TreeChart"] = 21] = "TreeChart";
    DashboardWidgetTypeEnum[DashboardWidgetTypeEnum["DigitChart"] = 22] = "DigitChart";
    DashboardWidgetTypeEnum[DashboardWidgetTypeEnum["ActiveTotalChart"] = 23] = "ActiveTotalChart";
    DashboardWidgetTypeEnum[DashboardWidgetTypeEnum["DashboardWidgetTypeEnum"] = 24] = "DashboardWidgetTypeEnum";
    DashboardWidgetTypeEnum[DashboardWidgetTypeEnum["Flat"] = 25] = "Flat"; // NEW added
})(DashboardWidgetTypeEnum = exports.DashboardWidgetTypeEnum || (exports.DashboardWidgetTypeEnum = {}));
